# -*- coding: utf-8 -*-
"""kpmg data insights

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1taQ_UkzM8Jnh5kYJQnBhFuJQjTdcFdzW
"""

#imported packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#below function allows the program to access a csv file from kpmg folder within google drive using the csv name as a parameter
def get_data(csvName):
    from google.colab import drive
    drive.mount('/content/gdrive',force_remount=True) #remove the remount if you get it all at once
    path='gdrive/My Drive/kpmg/'+csvName
    print(path
          )
    dat=pd.read_csv(path)
    return dat

customer_list = get_data('CustomerList.csv')

#list of all affluent customers (total = 241)
affluentData = customer_list[(customer_list['Unnamed: 7'] == "Affluent Customer")]

#list of all high net worth customers (total = 251)
highNetWorthData = customer_list[(customer_list['Unnamed: 7'] == "High Net Worth")]

#list of all people who don't have cars (total = 507)
ownsCarData = customer_list[(customer_list['Unnamed: 9'] == "No")]

#retrieves the name of the customer in a specified row
def getName(row):
  names = customer_list[row:row+1]
  return str(names)

#prints the people who don't own cars AND have either a high net worth or are affluent customers (total = 253)
i = 1
for row in ownsCarData:
  if getName(i) in highNetWorthData or getName(i) in affluentData:
    print(getName(i))
    print("")
    i = i+1

#distribution of wealth segments amongst all customers
labels = 'High Net Worth Customers', 'Mass Customers', 'Affluent Customers'
sizes = [250, 510, 240]
colors = ['gold', 'yellowgreen', 'lightcoral']

plt.pie(sizes, labels=labels, colors=colors,
autopct='%1.1f%%', shadow=True, startangle=140)

plt.axis('equal')
plt.show()

#percent of high net worth and affluent customers who also don't own cars
labels = 'High Net Worth and Affluent customers with cars', 'High Net Worth and Affluent customers without cars'
sizes = [239, 251]
colors = ['lightcoral', 'lightskyblue']
explode = (0.1, 0)

plt.pie(sizes,explode = explode, labels=labels, colors=colors,
autopct='%1.1f%%', shadow=True, startangle=140)

plt.axis('equal')
plt.show()

#final outlook
labels = 'Targeted customers', 'Remaining customers'
sizes = [251, 749]
colors = ['yellowgreen', 'gold']
explode = (0.1, 0)

plt.pie(sizes, explode = explode, labels=labels, colors=colors,
autopct='%1.1f%%', shadow=True, startangle=140)

plt.axis('equal')
plt.show()